version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HTTP_HOST: "0.0.0.0"
      HTTP_PORT: "8080"
      DB_NAME: "study"
      DB_INSTANCE_CONNECTION_NAME: "study-connection"
      JDBC_URL: "jdbc:postgresql://db:5432/study"
      DRIVER_CLASS_NAME: "org.postgresql.Driver"
      DB_USER_NAME: "any-username"
      DB_USER_PASSWORD: "any-password"
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_DB: "study"
      POSTGRES_USER: "any-username"
      POSTGRES_PASSWORD: "any-password"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
