services:
  db:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_DB: "study"
      POSTGRES_USER: "any-username"
      POSTGRES_PASSWORD: "any-password"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
